In [2]:
## TEXT CLASSIFICATION

In [3]:
import nltk
import string

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import wordnet

In [10]:
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [11]:
str1 = " I am learning machine learning. Natural language processing is part of machine learning and it is interesting ! "

In [12]:
str1 = str1.lower()

In [13]:
str1 = str1.strip()

In [14]:
str1

'i am learning machine learning. natural language processing is part of machine learning and it is interesting !'

In [15]:
sent = sent_tokenize(str1)
print(sent)

['i am learning machine learning.', 'natural language processing is part of machine learning and it is interesting !']

In [16]:
sent[1]

'natural language processing is part of machine learning and it is interesting !'

In [17]:
word = word_tokenize(str1)
print(word)

['i', 'am', 'learning', 'machine', 'learning', '.', 'natural', 'language', 'processing', 'is', 'part', 'of', 'machine', 'learning', 'and', 'it', 'is', 'interesting', '!']

In [62]:
#stopwords.words('english')

In [19]:
word_stop = [i for i in word if i not in stopwords.words('english')]
print(word_stop)

['learning', 'machine', 'learning', '.', 'natural', 'language', 'processing', 'part', 'machine', 'learning', 'interesting', '!']

In [20]:
PS = PorterStemmer()
word_stem = [PS.stem(i) for i in word_stop]
print(word_stem)

['learn', 'machin', 'learn', '.', 'natur', 'languag', 'process', 'part', 'machin', 'learn', 'interest', '!']

In [21]:
LM = WordNetLemmatizer()
word_lem = [LM.lemmatize(i) for i in word_stem]
print(word_lem)

['learn', 'machin', 'learn', '.', 'natur', 'languag', 'process', 'part', 'machin', 'learn', 'interest', '!']

In [24]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [26]:
pos_tags = nltk.pos_tag(word_lem)
print(pos_tags)

[('learn', 'NN'), ('machin', 'NN'), ('learn', 'NN'), ('.', '.'), ('natur', 'JJ'), ('languag', 'JJ'), ('process', 'NN'), ('part', 'NN'), ('machin', 'NN'), ('learn', 'JJ'), ('interest', 'NN'), ('!', '.')]

In [27]:
## PROJECT CLASSIFICATION

In [63]:
import pandas as pd
import numpy as np

from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import nltk

In [64]:
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
df = pd.read_csv(url,sep='\t', names=['label', 'message'])

In [65]:
df.shape

(5572, 2)

In [66]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [67]:
df['message'][1]

'Ok lar... Joking wif u oni...'

In [68]:
df.columns

Index(['label', 'message'], dtype='object')

In [69]:
df['label'].unique()

array(['ham', 'spam'], dtype=object)

In [70]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [71]:
def process(text):
  text = text.lower()
  text = "".join([i for i in text if i not in string.punctuation])
  tokens = word_tokenize(text)
  tokens = [i for i in tokens if i not in stopwords.words('english')]
  return " ".join(tokens)

In [72]:
process(df['message'][0])

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [73]:
df['message_clean'] = df['message'].apply(process)

In [74]:
vector = TfidfVectorizer()
x = vector.fit_transform(df['message_clean'])

In [75]:
dense_array = x.toarray()

# 2. Extract feature names (words) to use as column headers
feature_names = vector.get_feature_names_out()

# 3. Create the DataFrame
df_tfidf = pd.DataFrame(dense_array, columns=feature_names)

print(df_tfidf)

      008704050406  0089my  0121  01223585236  ...  zouk  zyada  üll  〨ud
0              0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
1              0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
2              0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
3              0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
4              0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
...            ...     ...   ...          ...  ...   ...    ...  ...  ...
5567           0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
5568           0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
5569           0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
5570           0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0
5571           0.0     0.0   0.0          0.0  ...   0.0    0.0  0.0  0.0

[5572 rows x 9430 columns]

In [76]:
y = df['label'].map({'ham':0, 'spam':1})

In [77]:
y = df['label'].values

In [78]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1, random_state=42)

In [79]:
NB = MultinomialNB()
NB.fit(x_train, y_train)

MultinomialNB()

In [80]:
pred = NB.predict(x_test)

In [81]:
accuracy_score(y_test, pred)

0.967741935483871

In [82]:
new_messages = ["Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."]

# 1. Transform the new text using the same vectorizer
new_messages_tfidf = vector.transform(new_messages)

# 2. Predict the labels
predicted_labels = NB.predict(new_messages_tfidf)

print(predicted_labels)

['ham']